//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ContactoCliente
    {
        public int idContactabilidad { get; set; }
        public int idColaborador { get; set; }
        public int idCliente { get; set; }
        public int idProducto { get; set; }
        public System.DateTime fechaContactoCliente { get; set; }
        public string comentarioContactoCliente { get; set; }
        public string estadoContactoCliente { get; set; }
    
        public virtual tb_Cliente tb_Cliente { get; set; }
        public virtual tb_Colaborador tb_Colaborador { get; set; }
        public virtual tb_Producto tb_Producto { get; set; }
    }
}
