//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Meta
    {
        public int idRol { get; set; }
        public int idSemanaPlan { get; set; }
        public int totalMeta { get; set; }
        public int idProducto { get; set; }
    
        public virtual tb_Producto tb_Producto { get; set; }
        public virtual tb_Rol tb_Rol { get; set; }
        public virtual tb_SemanaPlanificada tb_SemanaPlanificada { get; set; }
    }
}
