//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppEF.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTarjeta()
        {
            this.tbViaje = new HashSet<tbViaje>();
        }
    
        public int idTarjeta { get; set; }
        public string numeroTarjeta { get; set; }
        public string tipoTarjeta { get; set; }
        public string modoPago { get; set; }
        public string fechaVencimiento { get; set; }
        public int idCliente { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbViaje> tbViaje { get; set; }
    }
}
